version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Europe/Bratislava"
    open-pull-requests-limit: 100
    reviewers:
      - "branislavmalo"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"