version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: jump
      POSTGRES_PASSWORD: soft
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build:
      context: ..
      dockerfile: composefiles/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: jump
      SPRING_DATASOURCE_PASSWORD: soft
    networks:
      - backend

networks:
  backend:
    driver: bridge
