---
name: Super-Linter

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create checkstyle directory
        run: |
          mkdir -p ${{ github.workspace }}/.github/linters
          curl -o "${{ github.workspace }}/.github/linters/checkstyle.xml" \
            "https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/sun_checks.xml"
          
          sed -i 's/<property name="max" value="80"\/>/<property name="max" value="120"\/>/' \
            "${{ github.workspace }}/.github/linters/checkstyle.xml"
          
          sed -i '/<module name="JavadocPackage"\/>/c\<module name="JavadocPackage"><property \
            name="severity" value="ignore"/></module>' "${{ github.workspace }}/.github/linters/checkstyle.xml"
          
          sed -i '/<module name="HiddenField">/a\ <property name="ignoreConstructorParameter" value="true"/>' \
            "${{ github.workspace }}/.github/linters/checkstyle.xml"
          
          sed -i '/<module name="JavadocMethod"\/>/d' "${{ github.workspace }}/.github/linters/checkstyle.xml"
          sed -i '/<module name="JavadocType"\/>/d' "${{ github.workspace }}/.github/linters/checkstyle.xml"
          sed -i '/<module name="JavadocVariable"\/>/d' "${{ github.workspace }}/.github/linters/checkstyle.xml"

      - name: Super-Linter
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false  # Only lint changed files
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Enable specific linters for Java
          VALIDATE_JAVA: true
          VALIDATE_MARKDOWN: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
          # Java-specific settings
          JAVA_FILE_NAME: checkstyle.xml